### ISSUE TITLE
int value is incorrect on Windows

### ISSUE THREAD

**Issue by xlongshu** [synodriver/fast-bencode#3]
```python
import bencode
meta = {"intA": 2147483647, "intB": 2147483648}
print(bencode.bencode(meta))
```
- Windows
`b'd4:intAi2147483647e4:intBi-2147483648ee'`

- Linux
`b'd4:intAi2147483647e4:intBi2147483648ee'`

**Comment by fxj368** [comment]
This seems to be due to the C int32's range. If I make a copy of "bencode.py" and import bencode from it, the result will be correct.

```python
from bencode import bencode
print(bencode(2147483647))
print(bencode(2147483648))
print(bencode(11856280181))
``` 

Result:
`b'i2147483647e'
b'i-2147483648e'
b'i-1028621707e'`

Result from the copied "bencode.py":
`b'i2147483647e'
b'i2147483648e'
b'i11856280181e'`

**Comment by synodriver** [comment]
Sorry for the late reply. It seems PyOS_snprintf does not take very large int into account. or should we just use PyLongObject instead of c int？

**Comment by synodriver** [comment]
How about [this one](https://github.com/synodriver/fast-bencode/actions/runs/11348613160/job/31562789987)?

**Comment by fxj368** [comment]
> How about [this one](https://github.com/synodriver/fast-bencode/actions/runs/11348613160/job/31562789987)?

Thanks a lot, it works great for me. (I tried it in Python 3.11, on Windows 10 22H2 x64)

**Comment by synodriver** [comment]
Ok, I'll release a new version later.

**Comment by synodriver** [comment]
1.1.7 is ready.
